[tox]
envlist = py{310,311,312,313,314}
isolated_build = true
skip_missing_interpreters = true

[testenv]
extras =
    web
deps =
    pytest>=8.0
    pytest-cov>=5.0
    pytest-xdist>=3.0
commands =
    pytest tests/ -v -n auto {posargs}
